name: ecocollect_rwanda
description: EcoCollect Rwanda — Mobile E-Waste Collection & Recycling Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^8.0.0
  image_picker: ^1.0.4
  geolocator: ^14.1.1
  geocoding: ^5.0.0
  url_launcher: ^6.2.1
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  intl: ^0.20.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  percent_indicator: ^4.2.3
  flutter_animate: ^4.3.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
